apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Release.Namespace | quote}}
spec:
  template:
    metadata:
      annotations:
        # disable scaling for the solver service to make sure running jobs are handled properly
        # this could be improved by splitting this service into two, on for handling requests which could be scaled
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      serviceAccountName: "{{ .Chart.Name }}-serviceaccount"
      containers:
        - image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          ports:
            - containerPort: 8080
          env:
            - name: PGHOST
              value: "solvers-postgres-postgresql.project.svc.cluster.local"

            - name: PGDATABASE
              value: "postgres"

            - name: PGUSER
              value: "postgres"

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: solvers-postgres-postgresql
                  key: postgres-password
                  optional: false

            - name: PGPORT
              value: "5432"

            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-secret
                  optional: false
