apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Release.Namespace | quote}}
spec:
  template:
    spec:
      serviceAccountName: "{{ .Chart.Name }}-serviceaccount"
      containers:
        - image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          ports:
            - containerPort: 8080
