apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Release.Namespace | quote}}
spec:
  template:
    spec:
      serviceAccountName: "{{ .Chart.Name }}-serviceaccount"
      containers:
        - image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          ports:
            - containerPort: 8080
          env:
            - name: PGHOST
              value: "solvers-postgres-postgresql.project.svc.cluster.local"

            - name: PGDATABASE
              value: "postgres"

            - name: PGUSER
              value: "postgres"

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: solvers-postgres-postgresql
                  key: postgres-password
                  optional: false

            - name: PGPORT
              value: "5432"
