apiVersion: v1
kind: ServiceAccount
metadata:
  metadata:
  name: "{{ .Chart.Name }}-serviceaccount"
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: mzn-solver-creator
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["create", "get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mzn-solver-creator
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mzn-solver-creator
subjects:
- kind: ServiceAccount
  name: "{{ .Chart.Name }}-serviceaccount"
  namespace: {{ .Release.Namespace | quote }}
