apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: auth
build:
  artifacts:
  - image: dev.local/auth
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: auth-release
        chartPath: helm
        namespace: "project"
        createNamespace: true
        setValueTemplates:
          projectDomain: "{{.PROJECT_DOMAIN}}"

profiles:
  - name: production
    build:
      tagPolicy:
        gitCommit: {}
      artifacts:
      - image: ghcr.io/yousofmersal/dm885_auth-service
    deploy:
      helm:
        releases:
          - name: auth-release
            chartPath: helm
            setValues:
              image:
                repository: ghcr.io/yousofmersal/dm885_auth
