apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: auth
build:
  artifacts:
  - image: dev.local/auth
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: auth
        chartPath: helm
        namespace: "project"
        createNamespace: true
        setValueTemplates:
          projectDomain: "{{.PROJECT_DOMAIN}}"
