name: 'Terraform development'

on:
  push:

# defaults:
#   run:
#     working-directory: ./terraform/development

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

