apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Chart.Name }}-routes"
  namespace: {{.Release.Namespace}}
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
  - knative-serving/knative-ingress-gateway
  # Set host to the domain name that you own.
  hosts:
  - {{ .Values.projectDomain }}
  http:
  - match:
    - uri:
        prefix: "/api/v1/auth"
    rewrite:
      # Rewrite the original host header to the host header of Search service
      # in order to redirect requests to Search service.
      authority: "{{ .Chart.Name }}.{{ .Values.projectDomain }}"
    route:
      # Basically here we redirect the request to the cluster entry again with
      # updated header "search-service.default.example.com" so the request will
      # eventually be directed to Search service.
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100
