apiVersion: v1
kind: ServiceAccount
metadata:
  metadata:
  name: "{{ .Chart.Name }}-serviceaccount"
  namespace: {{.Release.Namespace | quote}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Release.Namespace | quote}}
  name: auth-service-creator
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-creator
  namespace: {{.Release.Namespace | quote}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auth-service-creator
subjects:
  - kind: ServiceAccount
    name: "{{ .Chart.Name }}-serviceaccount"
    namespace: {{.Release.Namespace | quote}}
