apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: mq-all
requires:
  - configs: []
    path: ./consumer/skaffold.yaml
  - configs: []
    path: ./producer/skaffold.yaml
  - configs: []
    path: ./mzn-controller/skaffold.yaml
