apiVersion: v1
kind: Pod
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Release.Namespace | quote}}
spec:
  serviceAccountName: {{ .Chart.Name }}-serviceaccount
  containers:
    - name: {{.Chart.Name}}
      image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
      env:
        - name: RABBIT_HOST
          valueFrom:
            secretKeyRef:
              name: {{.Values.rabbitmq.user_secrets | quote}}
              key: "host"
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: {{.Values.rabbitmq.user_secrets | quote}}
              key: "username"
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: {{.Values.rabbitmq.user_secrets | quote}}
              key: "password"
        - name: RABBIT_PORT
          valueFrom:
            secretKeyRef:
              name: {{.Values.rabbitmq.user_secrets | quote}}
              key: "port"
        - name: RABBIT_URL
          value: "amqp://$(RABBIT_USER):$(RABBIT_PASS)@$(RABBIT_HOST):$(RABBIT_PORT)"
