apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: dev.local/frontend
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: frontend-release
        chartPath: helm
        namespace: "project"
        createNamespace: true
        setValueTemplates:
          projectDomain: "{{.PROJECT_DOMAIN}}"
          publicDomain: "{{.PROJECT_DOMAIN}}"

profiles:
  - name: latest
    build:
      tagPolicy:
        sha256: {}
      artifacts:
      - image: ghcr.io/yousofmersal/dm885_frontend
        docker:
          dockerfile: Dockerfile
          cacheFrom:
            - ghcr.io/yousofmersal/dm885_frontend:latest
  - name: production
    build:
      tagPolicy:
        gitCommit: {}
      artifacts:
      - image: ghcr.io/yousofmersal/dm885_frontend
    deploy:
      helm:
        releases:
          - name: frontend-release
            chartPath: helm
            namespace: "project"
            createNamespace: true
            setValues:
              image:
                repository: ghcr.io/yousofmersal/dm885_frontend
            setValueTemplates:
              projectDomain: "{{.PROJECT_DOMAIN}}"
              publicDomain: "{{.PUBLIC_DOMAIN}}"
