apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: ghcr.io/yousofmersal/dm885_frontend-service
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: frontend-release
        chartPath: helm
        namespace: "project"
        createNamespace: true
        setValueTemplates:
          projectDomain: "{{.PROJECT_DOMAIN}}"