apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: dev.local/frontend
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: frontend-release
        chartPath: helm
        namespace: "project"
        createNamespace: true
        setValueTemplates:
          projectDomain: "{{.PROJECT_DOMAIN}}"
          publicDomain: "{{.PUBLIC_DOMAIN}}"

profiles:
  - name: production
    build:
      tagPolicy:
        gitCommit: {}
      artifacts:
      - image: ghcr.io/yousofmersal/dm885_frontend
    deploy:
      helm:
        releases:
          - name: frontend-release
            chartPath: helm
            setValues:
              image:
                repository: ghcr.io/yousofmersal/dm885_frontend
