apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-service
  namespace: {{.Release.Namespace | quote}}
spec:
  template:
    spec:
      containers:
      - image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
