apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: producer
build:
  artifacts:
  - image: producer
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: producer-release
        chartPath: helm
        namespace: "project"
        createNamespace: true
        artifactOverrides:
          image: producer
        imageStrategy:
          helm: {}
