apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: auth-service
build:
  artifacts:
  - image: dev.local/auth-service
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: auth-service-release
        chartPath: helm
        namespace: "project"
        createNamespace: true
        setValueTemplates:
          projectDomain: "{{.PROJECT_DOMAIN}}"

profiles:
  - name: production
    build:
      tagPolicy:
        gitCommit: {}
      artifacts:
      - image: ghcr.io/yousofmersal/dm885_auth-service
