apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: api-service
build:
  artifacts:
  - image: dev.local/api-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "src/**/*.ts"
          dest: "."
deploy:
  helm:
    releases:
      - name: api-service-release
        chartPath: helm
        namespace: "project"
        createNamespace: true
profiles:
  - name: development
    activation:
      - command: dev
    patches:
      # Use Dockerfile.dev for development profile
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile.dev