name: auth-deploy
on:
  push:
    # branches:
    #   - main
    paths:
      - services/auth-service/**
      - .github/workflows/auth-deploy.yaml

env:
  PROJECT_ID: steam-airfoil-367315
  GKE_CLUSTER: steam-airfoil-367315-gke
  GKE_ZONE: europe-west8-b
  PROJECT_DOMAIN: dm885.qpqp.dk

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Skaffold
        run: curl -Lo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install /tmp/skaffold /usr/local/bin/

      - name: Run Skaffold build
        run: skaffold build -p production --file-output=image.json
        working-directory: ./services/auth-service

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get GKE credentials
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Run Skaffold deploy
        run: skaffold deploy -p production -a image.json
        working-directory: ./services/auth-service
