# The unit test file(s) should be placed inside a folder called test in the working directory specified
name: solvers-test
on:
  push:
    branches: [ main ]
    paths:
    - services/solvers-service/**
    - .github/workflows/solvers-testing.yaml
  pull_request:
    branches: [ main ]
    paths:
    - services/solvers-service/**
    - .github/workflows/solvers-testing.yaml
  workflow_dispatch:

# Only one job  that does the following
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    # Retrieve the code from our repository
    - name: Checkout
      uses: actions/checkout@v3

    # Download and set up Node.js version 19
    - name: Set up Node 19.x
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'

    # Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    # Clean install the required dependencies
    - name: Install dependencies
      run: npm ci
      working-directory: ./services/solvers-service

    # Run the tests
    - name: Test
      run: npm test
      working-directory: ./services/solvers-service
